//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:05:08 AM MSK 
//


package interfax.ifax;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codes1" type="{http://interfax.ru/ifax}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="codes2" type="{http://interfax.ru/ifax}ArrayOfString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "codes1",
        "codes2"
})
@XmlRootElement(name = "EstimateCompaniesDistances")
public class EstimateCompaniesDistances {

    protected ArrayOfString codes1;
    protected ArrayOfString codes2;

    /**
     * Gets the value of the codes1 property.
     *
     * @return possible object is
     * {@link ArrayOfString }
     */
    public ArrayOfString getCodes1() {
        return codes1;
    }

    /**
     * Sets the value of the codes1 property.
     *
     * @param value allowed object is
     *              {@link ArrayOfString }
     */
    public void setCodes1(ArrayOfString value) {
        this.codes1 = value;
    }

    /**
     * Gets the value of the codes2 property.
     *
     * @return possible object is
     * {@link ArrayOfString }
     */
    public ArrayOfString getCodes2() {
        return codes2;
    }

    /**
     * Sets the value of the codes2 property.
     *
     * @param value allowed object is
     *              {@link ArrayOfString }
     */
    public void setCodes2(ArrayOfString value) {
        this.codes2 = value;
    }

}
