//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:05:08 AM MSK 
//


package interfax.ifax;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="code1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="code2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maxManagedCompanies" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="minOwnershipPercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maxCompaniesWithSameAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maxCompaniesWithSamePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "code1",
        "code2",
        "maxManagedCompanies",
        "minOwnershipPercent",
        "maxCompaniesWithSameAddress",
        "maxCompaniesWithSamePhone"
})
@XmlRootElement(name = "FindCompaniesLinks")
public class FindCompaniesLinks {

    protected String code1;
    protected String code2;
    protected String maxManagedCompanies;
    protected String minOwnershipPercent;
    protected String maxCompaniesWithSameAddress;
    protected String maxCompaniesWithSamePhone;

    /**
     * Gets the value of the code1 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode1() {
        return code1;
    }

    /**
     * Sets the value of the code1 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode1(String value) {
        this.code1 = value;
    }

    /**
     * Gets the value of the code2 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode2() {
        return code2;
    }

    /**
     * Sets the value of the code2 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode2(String value) {
        this.code2 = value;
    }

    /**
     * Gets the value of the maxManagedCompanies property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxManagedCompanies() {
        return maxManagedCompanies;
    }

    /**
     * Sets the value of the maxManagedCompanies property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxManagedCompanies(String value) {
        this.maxManagedCompanies = value;
    }

    /**
     * Gets the value of the minOwnershipPercent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMinOwnershipPercent() {
        return minOwnershipPercent;
    }

    /**
     * Sets the value of the minOwnershipPercent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMinOwnershipPercent(String value) {
        this.minOwnershipPercent = value;
    }

    /**
     * Gets the value of the maxCompaniesWithSameAddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxCompaniesWithSameAddress() {
        return maxCompaniesWithSameAddress;
    }

    /**
     * Sets the value of the maxCompaniesWithSameAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxCompaniesWithSameAddress(String value) {
        this.maxCompaniesWithSameAddress = value;
    }

    /**
     * Gets the value of the maxCompaniesWithSamePhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxCompaniesWithSamePhone() {
        return maxCompaniesWithSamePhone;
    }

    /**
     * Sets the value of the maxCompaniesWithSamePhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxCompaniesWithSamePhone(String value) {
        this.maxCompaniesWithSamePhone = value;
    }

}
