//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:05:08 AM MSK 
//


package interfax.ifax;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sparkId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="inn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ogrn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vacancyStatus" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="publishedFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="publishedTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="maxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "sparkId",
        "inn",
        "ogrn",
        "vacancyStatus",
        "publishedFrom",
        "publishedTo",
        "maxNumber"
})
@XmlRootElement(name = "GetCompanyVacancies")
public class GetCompanyVacancies {

    protected String sparkId;
    protected String inn;
    protected String ogrn;
    protected int vacancyStatus;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishedFrom;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishedTo;
    protected String maxNumber;

    /**
     * Gets the value of the sparkId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSparkId() {
        return sparkId;
    }

    /**
     * Sets the value of the sparkId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSparkId(String value) {
        this.sparkId = value;
    }

    /**
     * Gets the value of the inn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the ogrn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOgrn() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOgrn(String value) {
        this.ogrn = value;
    }

    /**
     * Gets the value of the vacancyStatus property.
     */
    public int getVacancyStatus() {
        return vacancyStatus;
    }

    /**
     * Sets the value of the vacancyStatus property.
     */
    public void setVacancyStatus(int value) {
        this.vacancyStatus = value;
    }

    /**
     * Gets the value of the publishedFrom property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getPublishedFrom() {
        return publishedFrom;
    }

    /**
     * Sets the value of the publishedFrom property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setPublishedFrom(XMLGregorianCalendar value) {
        this.publishedFrom = value;
    }

    /**
     * Gets the value of the publishedTo property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getPublishedTo() {
        return publishedTo;
    }

    /**
     * Sets the value of the publishedTo property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setPublishedTo(XMLGregorianCalendar value) {
        this.publishedTo = value;
    }

    /**
     * Gets the value of the maxNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxNumber() {
        return maxNumber;
    }

    /**
     * Sets the value of the maxNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxNumber(String value) {
        this.maxNumber = value;
    }

}
