//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:05:08 AM MSK 
//


package interfax.ifax;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="regionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="exactSearch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="egrpoIncluded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "companyName",
        "regionCode",
        "exactSearch",
        "egrpoIncluded"
})
@XmlRootElement(name = "GetCompanyListByName")
public class GetCompanyListByName {

    protected String companyName;
    protected String regionCode;
    protected String exactSearch;
    protected String egrpoIncluded;

    /**
     * Gets the value of the companyName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the regionCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegionCode(String value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the exactSearch property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExactSearch() {
        return exactSearch;
    }

    /**
     * Sets the value of the exactSearch property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExactSearch(String value) {
        this.exactSearch = value;
    }

    /**
     * Gets the value of the egrpoIncluded property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEgrpoIncluded() {
        return egrpoIncluded;
    }

    /**
     * Sets the value of the egrpoIncluded property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEgrpoIncluded(String value) {
        this.egrpoIncluded = value;
    }

}
