//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:05:08 AM MSK 
//


package interfax.ifax;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="manager" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postIndex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fuzzySearch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="historySearch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="activeCompanySearch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="minProbability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="excludeBranch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "companyName",
        "manager",
        "postIndex",
        "address",
        "phone",
        "fuzzySearch",
        "historySearch",
        "activeCompanySearch",
        "minProbability",
        "excludeBranch"
})
@XmlRootElement(name = "IdentifyCompany")
public class IdentifyCompany {

    protected String companyName;
    protected String manager;
    protected String postIndex;
    protected String address;
    protected String phone;
    protected String fuzzySearch;
    protected String historySearch;
    protected String activeCompanySearch;
    protected String minProbability;
    protected String excludeBranch;

    /**
     * Gets the value of the companyName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the manager property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setManager(String value) {
        this.manager = value;
    }

    /**
     * Gets the value of the postIndex property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostIndex() {
        return postIndex;
    }

    /**
     * Sets the value of the postIndex property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostIndex(String value) {
        this.postIndex = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the phone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fuzzySearch property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFuzzySearch() {
        return fuzzySearch;
    }

    /**
     * Sets the value of the fuzzySearch property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFuzzySearch(String value) {
        this.fuzzySearch = value;
    }

    /**
     * Gets the value of the historySearch property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHistorySearch() {
        return historySearch;
    }

    /**
     * Sets the value of the historySearch property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHistorySearch(String value) {
        this.historySearch = value;
    }

    /**
     * Gets the value of the activeCompanySearch property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getActiveCompanySearch() {
        return activeCompanySearch;
    }

    /**
     * Sets the value of the activeCompanySearch property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActiveCompanySearch(String value) {
        this.activeCompanySearch = value;
    }

    /**
     * Gets the value of the minProbability property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMinProbability() {
        return minProbability;
    }

    /**
     * Sets the value of the minProbability property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMinProbability(String value) {
        this.minProbability = value;
    }

    /**
     * Gets the value of the excludeBranch property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExcludeBranch() {
        return excludeBranch;
    }

    /**
     * Sets the value of the excludeBranch property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExcludeBranch(String value) {
        this.excludeBranch = value;
    }

}
