//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:05:08 AM MSK 
//


package interfax.ifax;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the ru.interfax.ifax package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.interfax.ifax
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Authmethod }
     */
    public Authmethod createAuthmethod() {
        return new Authmethod();
    }

    /**
     * Create an instance of {@link AuthmethodResponse }
     */
    public AuthmethodResponse createAuthmethodResponse() {
        return new AuthmethodResponse();
    }

    /**
     * Create an instance of {@link End }
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link EndResponse }
     */
    public EndResponse createEndResponse() {
        return new EndResponse();
    }

    /**
     * Create an instance of {@link GetListRegion }
     */
    public GetListRegion createGetListRegion() {
        return new GetListRegion();
    }

    /**
     * Create an instance of {@link GetListRegionResponse }
     */
    public GetListRegionResponse createGetListRegionResponse() {
        return new GetListRegionResponse();
    }

    /**
     * Create an instance of {@link GetListOKFS }
     */
    public GetListOKFS createGetListOKFS() {
        return new GetListOKFS();
    }

    /**
     * Create an instance of {@link GetListOKFSResponse }
     */
    public GetListOKFSResponse createGetListOKFSResponse() {
        return new GetListOKFSResponse();
    }

    /**
     * Create an instance of {@link GetListOKOPF }
     */
    public GetListOKOPF createGetListOKOPF() {
        return new GetListOKOPF();
    }

    /**
     * Create an instance of {@link GetListOKOPFResponse }
     */
    public GetListOKOPFResponse createGetListOKOPFResponse() {
        return new GetListOKOPFResponse();
    }

    /**
     * Create an instance of {@link GetStateAccount }
     */
    public GetStateAccount createGetStateAccount() {
        return new GetStateAccount();
    }

    /**
     * Create an instance of {@link GetStateAccountResponse }
     */
    public GetStateAccountResponse createGetStateAccountResponse() {
        return new GetStateAccountResponse();
    }

    /**
     * Create an instance of {@link GetPurchases }
     */
    public GetPurchases createGetPurchases() {
        return new GetPurchases();
    }

    /**
     * Create an instance of {@link GetPurchasesResponse }
     */
    public GetPurchasesResponse createGetPurchasesResponse() {
        return new GetPurchasesResponse();
    }

    /**
     * Create an instance of {@link FindCompanyByCode }
     */
    public FindCompanyByCode createFindCompanyByCode() {
        return new FindCompanyByCode();
    }

    /**
     * Create an instance of {@link FindCompanyByCodeResponse }
     */
    public FindCompanyByCodeResponse createFindCompanyByCodeResponse() {
        return new FindCompanyByCodeResponse();
    }

    /**
     * Create an instance of {@link GetCompanyShortReport }
     */
    public GetCompanyShortReport createGetCompanyShortReport() {
        return new GetCompanyShortReport();
    }

    /**
     * Create an instance of {@link GetCompanyShortReportResponse }
     */
    public GetCompanyShortReportResponse createGetCompanyShortReportResponse() {
        return new GetCompanyShortReportResponse();
    }

    /**
     * Create an instance of {@link GetCompanyExtendedReport }
     */
    public GetCompanyExtendedReport createGetCompanyExtendedReport() {
        return new GetCompanyExtendedReport();
    }

    /**
     * Create an instance of {@link GetCompanyExtendedReportResponse }
     */
    public GetCompanyExtendedReportResponse createGetCompanyExtendedReportResponse() {
        return new GetCompanyExtendedReportResponse();
    }

    /**
     * Create an instance of {@link GetCompanySparkRisksReport }
     */
    public GetCompanySparkRisksReport createGetCompanySparkRisksReport() {
        return new GetCompanySparkRisksReport();
    }

    /**
     * Create an instance of {@link GetCompanySparkRisksReportResponse }
     */
    public GetCompanySparkRisksReportResponse createGetCompanySparkRisksReportResponse() {
        return new GetCompanySparkRisksReportResponse();
    }

    /**
     * Create an instance of {@link GetCompanySparkRisksReportXML }
     */
    public GetCompanySparkRisksReportXML createGetCompanySparkRisksReportXML() {
        return new GetCompanySparkRisksReportXML();
    }

    /**
     * Create an instance of {@link GetCompanySparkRisksReportXMLResponse }
     */
    public GetCompanySparkRisksReportXMLResponse createGetCompanySparkRisksReportXMLResponse() {
        return new GetCompanySparkRisksReportXMLResponse();
    }

    /**
     * Create an instance of {@link GetCompanyLicenses }
     */
    public GetCompanyLicenses createGetCompanyLicenses() {
        return new GetCompanyLicenses();
    }

    /**
     * Create an instance of {@link GetCompanyLicensesResponse }
     */
    public GetCompanyLicensesResponse createGetCompanyLicensesResponse() {
        return new GetCompanyLicensesResponse();
    }

    /**
     * Create an instance of {@link GetCompanyStructure }
     */
    public GetCompanyStructure createGetCompanyStructure() {
        return new GetCompanyStructure();
    }

    /**
     * Create an instance of {@link GetCompanyStructureResponse }
     */
    public GetCompanyStructureResponse createGetCompanyStructureResponse() {
        return new GetCompanyStructureResponse();
    }

    /**
     * Create an instance of {@link GetCompanyCoownersHistory }
     */
    public GetCompanyCoownersHistory createGetCompanyCoownersHistory() {
        return new GetCompanyCoownersHistory();
    }

    /**
     * Create an instance of {@link GetCompanyCoownersHistoryResponse }
     */
    public GetCompanyCoownersHistoryResponse createGetCompanyCoownersHistoryResponse() {
        return new GetCompanyCoownersHistoryResponse();
    }

    /**
     * Create an instance of {@link GetCompanySubsidiariesHistory }
     */
    public GetCompanySubsidiariesHistory createGetCompanySubsidiariesHistory() {
        return new GetCompanySubsidiariesHistory();
    }

    /**
     * Create an instance of {@link GetCompanySubsidiariesHistoryResponse }
     */
    public GetCompanySubsidiariesHistoryResponse createGetCompanySubsidiariesHistoryResponse() {
        return new GetCompanySubsidiariesHistoryResponse();
    }

    /**
     * Create an instance of {@link GetOwnershipHierarchy }
     */
    public GetOwnershipHierarchy createGetOwnershipHierarchy() {
        return new GetOwnershipHierarchy();
    }

    /**
     * Create an instance of {@link GetOwnershipHierarchyResponse }
     */
    public GetOwnershipHierarchyResponse createGetOwnershipHierarchyResponse() {
        return new GetOwnershipHierarchyResponse();
    }

    /**
     * Create an instance of {@link GetCompanyManagementBodiesHistory }
     */
    public GetCompanyManagementBodiesHistory createGetCompanyManagementBodiesHistory() {
        return new GetCompanyManagementBodiesHistory();
    }

    /**
     * Create an instance of {@link GetCompanyManagementBodiesHistoryResponse }
     */
    public GetCompanyManagementBodiesHistoryResponse createGetCompanyManagementBodiesHistoryResponse() {
        return new GetCompanyManagementBodiesHistoryResponse();
    }

    /**
     * Create an instance of {@link GetCompanyPredecessorSuccessor }
     */
    public GetCompanyPredecessorSuccessor createGetCompanyPredecessorSuccessor() {
        return new GetCompanyPredecessorSuccessor();
    }

    /**
     * Create an instance of {@link GetCompanyPredecessorSuccessorResponse }
     */
    public GetCompanyPredecessorSuccessorResponse createGetCompanyPredecessorSuccessorResponse() {
        return new GetCompanyPredecessorSuccessorResponse();
    }

    /**
     * Create an instance of {@link GetCompanyCounterparties }
     */
    public GetCompanyCounterparties createGetCompanyCounterparties() {
        return new GetCompanyCounterparties();
    }

    /**
     * Create an instance of {@link GetCompanyCounterpartiesResponse }
     */
    public GetCompanyCounterpartiesResponse createGetCompanyCounterpartiesResponse() {
        return new GetCompanyCounterpartiesResponse();
    }

    /**
     * Create an instance of {@link GetCompanyPaymentDiscipline }
     */
    public GetCompanyPaymentDiscipline createGetCompanyPaymentDiscipline() {
        return new GetCompanyPaymentDiscipline();
    }

    /**
     * Create an instance of {@link GetCompanyPaymentDisciplineResponse }
     */
    public GetCompanyPaymentDisciplineResponse createGetCompanyPaymentDisciplineResponse() {
        return new GetCompanyPaymentDisciplineResponse();
    }

    /**
     * Create an instance of {@link GetCompanyExecutionProceedings }
     */
    public GetCompanyExecutionProceedings createGetCompanyExecutionProceedings() {
        return new GetCompanyExecutionProceedings();
    }

    /**
     * Create an instance of {@link GetCompanyExecutionProceedingsResponse }
     */
    public GetCompanyExecutionProceedingsResponse createGetCompanyExecutionProceedingsResponse() {
        return new GetCompanyExecutionProceedingsResponse();
    }

    /**
     * Create an instance of {@link GetCompanyPledges }
     */
    public GetCompanyPledges createGetCompanyPledges() {
        return new GetCompanyPledges();
    }

    /**
     * Create an instance of {@link GetCompanyPledgesResponse }
     */
    public GetCompanyPledgesResponse createGetCompanyPledgesResponse() {
        return new GetCompanyPledgesResponse();
    }

    /**
     * Create an instance of {@link GetCompanyLeasings }
     */
    public GetCompanyLeasings createGetCompanyLeasings() {
        return new GetCompanyLeasings();
    }

    /**
     * Create an instance of {@link GetCompanyLeasingsResponse }
     */
    public GetCompanyLeasingsResponse createGetCompanyLeasingsResponse() {
        return new GetCompanyLeasingsResponse();
    }

    /**
     * Create an instance of {@link GetCompanyStateContracts }
     */
    public GetCompanyStateContracts createGetCompanyStateContracts() {
        return new GetCompanyStateContracts();
    }

    /**
     * Create an instance of {@link GetCompanyStateContractsResponse }
     */
    public GetCompanyStateContractsResponse createGetCompanyStateContractsResponse() {
        return new GetCompanyStateContractsResponse();
    }

    /**
     * Create an instance of {@link GetCompanyArbitrationSummary }
     */
    public GetCompanyArbitrationSummary createGetCompanyArbitrationSummary() {
        return new GetCompanyArbitrationSummary();
    }

    /**
     * Create an instance of {@link GetCompanyArbitrationSummaryResponse }
     */
    public GetCompanyArbitrationSummaryResponse createGetCompanyArbitrationSummaryResponse() {
        return new GetCompanyArbitrationSummaryResponse();
    }

    /**
     * Create an instance of {@link GetCompanyRiskFactors }
     */
    public GetCompanyRiskFactors createGetCompanyRiskFactors() {
        return new GetCompanyRiskFactors();
    }

    /**
     * Create an instance of {@link GetCompanyRiskFactorsResponse }
     */
    public GetCompanyRiskFactorsResponse createGetCompanyRiskFactorsResponse() {
        return new GetCompanyRiskFactorsResponse();
    }

    /**
     * Create an instance of {@link GetCompanyVacancies }
     */
    public GetCompanyVacancies createGetCompanyVacancies() {
        return new GetCompanyVacancies();
    }

    /**
     * Create an instance of {@link GetCompanyVacanciesResponse }
     */
    public GetCompanyVacanciesResponse createGetCompanyVacanciesResponse() {
        return new GetCompanyVacanciesResponse();
    }

    /**
     * Create an instance of {@link GetCompanyAccountingReportDateList }
     */
    public GetCompanyAccountingReportDateList createGetCompanyAccountingReportDateList() {
        return new GetCompanyAccountingReportDateList();
    }

    /**
     * Create an instance of {@link GetCompanyAccountingReportDateListResponse }
     */
    public GetCompanyAccountingReportDateListResponse createGetCompanyAccountingReportDateListResponse() {
        return new GetCompanyAccountingReportDateListResponse();
    }

    /**
     * Create an instance of {@link GetCompanyAccountingReport }
     */
    public GetCompanyAccountingReport createGetCompanyAccountingReport() {
        return new GetCompanyAccountingReport();
    }

    /**
     * Create an instance of {@link GetCompanyAccountingReportResponse }
     */
    public GetCompanyAccountingReportResponse createGetCompanyAccountingReportResponse() {
        return new GetCompanyAccountingReportResponse();
    }

    /**
     * Create an instance of {@link GetBankAccountingReport101102 }
     */
    public GetBankAccountingReport101102 createGetBankAccountingReport101102() {
        return new GetBankAccountingReport101102();
    }

    /**
     * Create an instance of {@link GetBankAccountingReport101102Response }
     */
    public GetBankAccountingReport101102Response createGetBankAccountingReport101102Response() {
        return new GetBankAccountingReport101102Response();
    }

    /**
     * Create an instance of {@link GetCompanyFinancialAnalysis }
     */
    public GetCompanyFinancialAnalysis createGetCompanyFinancialAnalysis() {
        return new GetCompanyFinancialAnalysis();
    }

    /**
     * Create an instance of {@link GetCompanyFinancialAnalysisResponse }
     */
    public GetCompanyFinancialAnalysisResponse createGetCompanyFinancialAnalysisResponse() {
        return new GetCompanyFinancialAnalysisResponse();
    }

    /**
     * Create an instance of {@link GetCompanySanctionList }
     */
    public GetCompanySanctionList createGetCompanySanctionList() {
        return new GetCompanySanctionList();
    }

    /**
     * Create an instance of {@link GetCompanySanctionListResponse }
     */
    public GetCompanySanctionListResponse createGetCompanySanctionListResponse() {
        return new GetCompanySanctionListResponse();
    }

    /**
     * Create an instance of {@link CheckCompany115FederalLaw }
     */
    public CheckCompany115FederalLaw createCheckCompany115FederalLaw() {
        return new CheckCompany115FederalLaw();
    }

    /**
     * Create an instance of {@link CheckCompany115FederalLawResponse }
     */
    public CheckCompany115FederalLawResponse createCheckCompany115FederalLawResponse() {
        return new CheckCompany115FederalLawResponse();
    }

    /**
     * Create an instance of {@link OrderCompanyBeneficiariesAndAffiliates }
     */
    public OrderCompanyBeneficiariesAndAffiliates createOrderCompanyBeneficiariesAndAffiliates() {
        return new OrderCompanyBeneficiariesAndAffiliates();
    }

    /**
     * Create an instance of {@link OrderCompanyBeneficiariesAndAffiliatesResponse }
     */
    public OrderCompanyBeneficiariesAndAffiliatesResponse createOrderCompanyBeneficiariesAndAffiliatesResponse() {
        return new OrderCompanyBeneficiariesAndAffiliatesResponse();
    }

    /**
     * Create an instance of {@link GetCompanyBeneficiariesAndAffiliates }
     */
    public GetCompanyBeneficiariesAndAffiliates createGetCompanyBeneficiariesAndAffiliates() {
        return new GetCompanyBeneficiariesAndAffiliates();
    }

    /**
     * Create an instance of {@link GetCompanyBeneficiariesAndAffiliatesResponse }
     */
    public GetCompanyBeneficiariesAndAffiliatesResponse createGetCompanyBeneficiariesAndAffiliatesResponse() {
        return new GetCompanyBeneficiariesAndAffiliatesResponse();
    }

    /**
     * Create an instance of {@link OrderCompaniesLinksInStateContracts }
     */
    public OrderCompaniesLinksInStateContracts createOrderCompaniesLinksInStateContracts() {
        return new OrderCompaniesLinksInStateContracts();
    }

    /**
     * Create an instance of {@link OrderCompaniesLinksInStateContractsResponse }
     */
    public OrderCompaniesLinksInStateContractsResponse createOrderCompaniesLinksInStateContractsResponse() {
        return new OrderCompaniesLinksInStateContractsResponse();
    }

    /**
     * Create an instance of {@link GetCompaniesLinksInStateContracts }
     */
    public GetCompaniesLinksInStateContracts createGetCompaniesLinksInStateContracts() {
        return new GetCompaniesLinksInStateContracts();
    }

    /**
     * Create an instance of {@link GetCompaniesLinksInStateContractsResponse }
     */
    public GetCompaniesLinksInStateContractsResponse createGetCompaniesLinksInStateContractsResponse() {
        return new GetCompaniesLinksInStateContractsResponse();
    }

    /**
     * Create an instance of {@link OrderEGRUL }
     */
    public OrderEGRUL createOrderEGRUL() {
        return new OrderEGRUL();
    }

    /**
     * Create an instance of {@link OrderEGRULResponse }
     */
    public OrderEGRULResponse createOrderEGRULResponse() {
        return new OrderEGRULResponse();
    }

    /**
     * Create an instance of {@link GetEGRULOrderList }
     */
    public GetEGRULOrderList createGetEGRULOrderList() {
        return new GetEGRULOrderList();
    }

    /**
     * Create an instance of {@link GetEGRULOrderListResponse }
     */
    public GetEGRULOrderListResponse createGetEGRULOrderListResponse() {
        return new GetEGRULOrderListResponse();
    }

    /**
     * Create an instance of {@link GetEGRULData }
     */
    public GetEGRULData createGetEGRULData() {
        return new GetEGRULData();
    }

    /**
     * Create an instance of {@link GetEGRULDataResponse }
     */
    public GetEGRULDataResponse createGetEGRULDataResponse() {
        return new GetEGRULDataResponse();
    }

    /**
     * Create an instance of {@link GetEGRULFormatData }
     */
    public GetEGRULFormatData createGetEGRULFormatData() {
        return new GetEGRULFormatData();
    }

    /**
     * Create an instance of {@link GetEGRULFormatDataResponse }
     */
    public GetEGRULFormatDataResponse createGetEGRULFormatDataResponse() {
        return new GetEGRULFormatDataResponse();
    }

    /**
     * Create an instance of {@link OrderEGRIP }
     */
    public OrderEGRIP createOrderEGRIP() {
        return new OrderEGRIP();
    }

    /**
     * Create an instance of {@link OrderEGRIPResponse }
     */
    public OrderEGRIPResponse createOrderEGRIPResponse() {
        return new OrderEGRIPResponse();
    }

    /**
     * Create an instance of {@link GetEGRIPOrderList }
     */
    public GetEGRIPOrderList createGetEGRIPOrderList() {
        return new GetEGRIPOrderList();
    }

    /**
     * Create an instance of {@link GetEGRIPOrderListResponse }
     */
    public GetEGRIPOrderListResponse createGetEGRIPOrderListResponse() {
        return new GetEGRIPOrderListResponse();
    }

    /**
     * Create an instance of {@link GetEGRIPData }
     */
    public GetEGRIPData createGetEGRIPData() {
        return new GetEGRIPData();
    }

    /**
     * Create an instance of {@link GetEGRIPDataResponse }
     */
    public GetEGRIPDataResponse createGetEGRIPDataResponse() {
        return new GetEGRIPDataResponse();
    }

    /**
     * Create an instance of {@link GetEGRIPFormatData }
     */
    public GetEGRIPFormatData createGetEGRIPFormatData() {
        return new GetEGRIPFormatData();
    }

    /**
     * Create an instance of {@link GetEGRIPFormatDataResponse }
     */
    public GetEGRIPFormatDataResponse createGetEGRIPFormatDataResponse() {
        return new GetEGRIPFormatDataResponse();
    }

    /**
     * Create an instance of {@link CheckCompanyStatus }
     */
    public CheckCompanyStatus createCheckCompanyStatus() {
        return new CheckCompanyStatus();
    }

    /**
     * Create an instance of {@link CheckCompanyStatusResponse }
     */
    public CheckCompanyStatusResponse createCheckCompanyStatusResponse() {
        return new CheckCompanyStatusResponse();
    }

    /**
     * Create an instance of {@link GetCompanyListByPhone }
     */
    public GetCompanyListByPhone createGetCompanyListByPhone() {
        return new GetCompanyListByPhone();
    }

    /**
     * Create an instance of {@link GetCompanyListByPhoneResponse }
     */
    public GetCompanyListByPhoneResponse createGetCompanyListByPhoneResponse() {
        return new GetCompanyListByPhoneResponse();
    }

    /**
     * Create an instance of {@link GetCompanyListByAddress }
     */
    public GetCompanyListByAddress createGetCompanyListByAddress() {
        return new GetCompanyListByAddress();
    }

    /**
     * Create an instance of {@link GetCompanyListByAddressResponse }
     */
    public GetCompanyListByAddressResponse createGetCompanyListByAddressResponse() {
        return new GetCompanyListByAddressResponse();
    }

    /**
     * Create an instance of {@link GetCompanyListByName }
     */
    public GetCompanyListByName createGetCompanyListByName() {
        return new GetCompanyListByName();
    }

    /**
     * Create an instance of {@link GetCompanyListByNameResponse }
     */
    public GetCompanyListByNameResponse createGetCompanyListByNameResponse() {
        return new GetCompanyListByNameResponse();
    }

    /**
     * Create an instance of {@link GetCompanyListByFIO }
     */
    public GetCompanyListByFIO createGetCompanyListByFIO() {
        return new GetCompanyListByFIO();
    }

    /**
     * Create an instance of {@link GetCompanyListByFIOResponse }
     */
    public GetCompanyListByFIOResponse createGetCompanyListByFIOResponse() {
        return new GetCompanyListByFIOResponse();
    }

    /**
     * Create an instance of {@link GetCompanyListByPersonFIO }
     */
    public GetCompanyListByPersonFIO createGetCompanyListByPersonFIO() {
        return new GetCompanyListByPersonFIO();
    }

    /**
     * Create an instance of {@link GetCompanyListByPersonFIOResponse }
     */
    public GetCompanyListByPersonFIOResponse createGetCompanyListByPersonFIOResponse() {
        return new GetCompanyListByPersonFIOResponse();
    }

    /**
     * Create an instance of {@link GetCompanyListByPersonINN }
     */
    public GetCompanyListByPersonINN createGetCompanyListByPersonINN() {
        return new GetCompanyListByPersonINN();
    }

    /**
     * Create an instance of {@link GetCompanyListByPersonINNResponse }
     */
    public GetCompanyListByPersonINNResponse createGetCompanyListByPersonINNResponse() {
        return new GetCompanyListByPersonINNResponse();
    }

    /**
     * Create an instance of {@link GetCompanyByDomain }
     */
    public GetCompanyByDomain createGetCompanyByDomain() {
        return new GetCompanyByDomain();
    }

    /**
     * Create an instance of {@link GetCompanyByDomainResponse }
     */
    public GetCompanyByDomainResponse createGetCompanyByDomainResponse() {
        return new GetCompanyByDomainResponse();
    }

    /**
     * Create an instance of {@link GetNewCompanies }
     */
    public GetNewCompanies createGetNewCompanies() {
        return new GetNewCompanies();
    }

    /**
     * Create an instance of {@link GetNewCompaniesResponse }
     */
    public GetNewCompaniesResponse createGetNewCompaniesResponse() {
        return new GetNewCompaniesResponse();
    }

    /**
     * Create an instance of {@link GetChangedCompanies }
     */
    public GetChangedCompanies createGetChangedCompanies() {
        return new GetChangedCompanies();
    }

    /**
     * Create an instance of {@link GetChangedCompaniesResponse }
     */
    public GetChangedCompaniesResponse createGetChangedCompaniesResponse() {
        return new GetChangedCompaniesResponse();
    }

    /**
     * Create an instance of {@link FindCompaniesLinks }
     */
    public FindCompaniesLinks createFindCompaniesLinks() {
        return new FindCompaniesLinks();
    }

    /**
     * Create an instance of {@link FindCompaniesLinksResponse }
     */
    public FindCompaniesLinksResponse createFindCompaniesLinksResponse() {
        return new FindCompaniesLinksResponse();
    }

    /**
     * Create an instance of {@link EstimateCompaniesDistances }
     */
    public EstimateCompaniesDistances createEstimateCompaniesDistances() {
        return new EstimateCompaniesDistances();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link EstimateCompaniesDistancesResponse }
     */
    public EstimateCompaniesDistancesResponse createEstimateCompaniesDistancesResponse() {
        return new EstimateCompaniesDistancesResponse();
    }

    /**
     * Create an instance of {@link FindEntrepreneurByCode }
     */
    public FindEntrepreneurByCode createFindEntrepreneurByCode() {
        return new FindEntrepreneurByCode();
    }

    /**
     * Create an instance of {@link FindEntrepreneurByCodeResponse }
     */
    public FindEntrepreneurByCodeResponse createFindEntrepreneurByCodeResponse() {
        return new FindEntrepreneurByCodeResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurListByFIO }
     */
    public GetEntrepreneurListByFIO createGetEntrepreneurListByFIO() {
        return new GetEntrepreneurListByFIO();
    }

    /**
     * Create an instance of {@link GetEntrepreneurListByFIOResponse }
     */
    public GetEntrepreneurListByFIOResponse createGetEntrepreneurListByFIOResponse() {
        return new GetEntrepreneurListByFIOResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurShortReport }
     */
    public GetEntrepreneurShortReport createGetEntrepreneurShortReport() {
        return new GetEntrepreneurShortReport();
    }

    /**
     * Create an instance of {@link GetEntrepreneurShortReportResponse }
     */
    public GetEntrepreneurShortReportResponse createGetEntrepreneurShortReportResponse() {
        return new GetEntrepreneurShortReportResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurExecutionProceedings }
     */
    public GetEntrepreneurExecutionProceedings createGetEntrepreneurExecutionProceedings() {
        return new GetEntrepreneurExecutionProceedings();
    }

    /**
     * Create an instance of {@link GetEntrepreneurExecutionProceedingsResponse }
     */
    public GetEntrepreneurExecutionProceedingsResponse createGetEntrepreneurExecutionProceedingsResponse() {
        return new GetEntrepreneurExecutionProceedingsResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurPledges }
     */
    public GetEntrepreneurPledges createGetEntrepreneurPledges() {
        return new GetEntrepreneurPledges();
    }

    /**
     * Create an instance of {@link GetEntrepreneurPledgesResponse }
     */
    public GetEntrepreneurPledgesResponse createGetEntrepreneurPledgesResponse() {
        return new GetEntrepreneurPledgesResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurLeasings }
     */
    public GetEntrepreneurLeasings createGetEntrepreneurLeasings() {
        return new GetEntrepreneurLeasings();
    }

    /**
     * Create an instance of {@link GetEntrepreneurLeasingsResponse }
     */
    public GetEntrepreneurLeasingsResponse createGetEntrepreneurLeasingsResponse() {
        return new GetEntrepreneurLeasingsResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurStateContracts }
     */
    public GetEntrepreneurStateContracts createGetEntrepreneurStateContracts() {
        return new GetEntrepreneurStateContracts();
    }

    /**
     * Create an instance of {@link GetEntrepreneurStateContractsResponse }
     */
    public GetEntrepreneurStateContractsResponse createGetEntrepreneurStateContractsResponse() {
        return new GetEntrepreneurStateContractsResponse();
    }

    /**
     * Create an instance of {@link GetEntrepreneurArbitrationSummary }
     */
    public GetEntrepreneurArbitrationSummary createGetEntrepreneurArbitrationSummary() {
        return new GetEntrepreneurArbitrationSummary();
    }

    /**
     * Create an instance of {@link GetEntrepreneurArbitrationSummaryResponse }
     */
    public GetEntrepreneurArbitrationSummaryResponse createGetEntrepreneurArbitrationSummaryResponse() {
        return new GetEntrepreneurArbitrationSummaryResponse();
    }

    /**
     * Create an instance of {@link CheckEntrepreneurStatus }
     */
    public CheckEntrepreneurStatus createCheckEntrepreneurStatus() {
        return new CheckEntrepreneurStatus();
    }

    /**
     * Create an instance of {@link CheckEntrepreneurStatusResponse }
     */
    public CheckEntrepreneurStatusResponse createCheckEntrepreneurStatusResponse() {
        return new CheckEntrepreneurStatusResponse();
    }

    /**
     * Create an instance of {@link GetNewEntrepreneurs }
     */
    public GetNewEntrepreneurs createGetNewEntrepreneurs() {
        return new GetNewEntrepreneurs();
    }

    /**
     * Create an instance of {@link GetNewEntrepreneursResponse }
     */
    public GetNewEntrepreneursResponse createGetNewEntrepreneursResponse() {
        return new GetNewEntrepreneursResponse();
    }

    /**
     * Create an instance of {@link GetChangedEntrepreneurs }
     */
    public GetChangedEntrepreneurs createGetChangedEntrepreneurs() {
        return new GetChangedEntrepreneurs();
    }

    /**
     * Create an instance of {@link GetChangedEntrepreneursResponse }
     */
    public GetChangedEntrepreneursResponse createGetChangedEntrepreneursResponse() {
        return new GetChangedEntrepreneursResponse();
    }

    /**
     * Create an instance of {@link GetSupplierStateContracts }
     */
    public GetSupplierStateContracts createGetSupplierStateContracts() {
        return new GetSupplierStateContracts();
    }

    /**
     * Create an instance of {@link GetSupplierStateContractsResponse }
     */
    public GetSupplierStateContractsResponse createGetSupplierStateContractsResponse() {
        return new GetSupplierStateContractsResponse();
    }

    /**
     * Create an instance of {@link GetEvotorRiskFactors }
     */
    public GetEvotorRiskFactors createGetEvotorRiskFactors() {
        return new GetEvotorRiskFactors();
    }

    /**
     * Create an instance of {@link GetEvotorRiskFactorsResponse }
     */
    public GetEvotorRiskFactorsResponse createGetEvotorRiskFactorsResponse() {
        return new GetEvotorRiskFactorsResponse();
    }

    /**
     * Create an instance of {@link MonActivate }
     */
    public MonActivate createMonActivate() {
        return new MonActivate();
    }

    /**
     * Create an instance of {@link MonActivateResponse }
     */
    public MonActivateResponse createMonActivateResponse() {
        return new MonActivateResponse();
    }

    /**
     * Create an instance of {@link MonGetCompaniesList }
     */
    public MonGetCompaniesList createMonGetCompaniesList() {
        return new MonGetCompaniesList();
    }

    /**
     * Create an instance of {@link MonGetCompaniesListResponse }
     */
    public MonGetCompaniesListResponse createMonGetCompaniesListResponse() {
        return new MonGetCompaniesListResponse();
    }

    /**
     * Create an instance of {@link MonDisable }
     */
    public MonDisable createMonDisable() {
        return new MonDisable();
    }

    /**
     * Create an instance of {@link MonDisableResponse }
     */
    public MonDisableResponse createMonDisableResponse() {
        return new MonDisableResponse();
    }

    /**
     * Create an instance of {@link MonDisableCompaniesList }
     */
    public MonDisableCompaniesList createMonDisableCompaniesList() {
        return new MonDisableCompaniesList();
    }

    /**
     * Create an instance of {@link MonDisableCompaniesListResponse }
     */
    public MonDisableCompaniesListResponse createMonDisableCompaniesListResponse() {
        return new MonDisableCompaniesListResponse();
    }

    /**
     * Create an instance of {@link MonGetEventsList }
     */
    public MonGetEventsList createMonGetEventsList() {
        return new MonGetEventsList();
    }

    /**
     * Create an instance of {@link MonGetEventsListResponse }
     */
    public MonGetEventsListResponse createMonGetEventsListResponse() {
        return new MonGetEventsListResponse();
    }

    /**
     * Create an instance of {@link MonGetCompanyEvents }
     */
    public MonGetCompanyEvents createMonGetCompanyEvents() {
        return new MonGetCompanyEvents();
    }

    /**
     * Create an instance of {@link MonGetCompanyEventsResponse }
     */
    public MonGetCompanyEventsResponse createMonGetCompanyEventsResponse() {
        return new MonGetCompanyEventsResponse();
    }

    /**
     * Create an instance of {@link IdentifyCompany }
     */
    public IdentifyCompany createIdentifyCompany() {
        return new IdentifyCompany();
    }

    /**
     * Create an instance of {@link IdentifyCompanyResponse }
     */
    public IdentifyCompanyResponse createIdentifyCompanyResponse() {
        return new IdentifyCompanyResponse();
    }

    /**
     * Create an instance of {@link GetPersonSparkRisksReport }
     */
    public GetPersonSparkRisksReport createGetPersonSparkRisksReport() {
        return new GetPersonSparkRisksReport();
    }

    /**
     * Create an instance of {@link GetPersonSparkRisksReportResponse }
     */
    public GetPersonSparkRisksReportResponse createGetPersonSparkRisksReportResponse() {
        return new GetPersonSparkRisksReportResponse();
    }

    /**
     * Create an instance of {@link ValidatePassport }
     */
    public ValidatePassport createValidatePassport() {
        return new ValidatePassport();
    }

    /**
     * Create an instance of {@link ValidatePassportResponse }
     */
    public ValidatePassportResponse createValidatePassportResponse() {
        return new ValidatePassportResponse();
    }

    /**
     * Create an instance of {@link GetBankruptPersonList }
     */
    public GetBankruptPersonList createGetBankruptPersonList() {
        return new GetBankruptPersonList();
    }

    /**
     * Create an instance of {@link GetBankruptPersonListResponse }
     */
    public GetBankruptPersonListResponse createGetBankruptPersonListResponse() {
        return new GetBankruptPersonListResponse();
    }

    /**
     * Create an instance of {@link GetBankruptPerson }
     */
    public GetBankruptPerson createGetBankruptPerson() {
        return new GetBankruptPerson();
    }

    /**
     * Create an instance of {@link GetBankruptPersonResponse }
     */
    public GetBankruptPersonResponse createGetBankruptPersonResponse() {
        return new GetBankruptPersonResponse();
    }

    /**
     * Create an instance of {@link GetPersonSanctionList }
     */
    public GetPersonSanctionList createGetPersonSanctionList() {
        return new GetPersonSanctionList();
    }

    /**
     * Create an instance of {@link GetPersonSanctionListResponse }
     */
    public GetPersonSanctionListResponse createGetPersonSanctionListResponse() {
        return new GetPersonSanctionListResponse();
    }

    /**
     * Create an instance of {@link GetPersonComplianceReport }
     */
    public GetPersonComplianceReport createGetPersonComplianceReport() {
        return new GetPersonComplianceReport();
    }

    /**
     * Create an instance of {@link GetPersonComplianceReportResponse }
     */
    public GetPersonComplianceReportResponse createGetPersonComplianceReportResponse() {
        return new GetPersonComplianceReportResponse();
    }

    /**
     * Create an instance of {@link MonPersonActivate }
     */
    public MonPersonActivate createMonPersonActivate() {
        return new MonPersonActivate();
    }

    /**
     * Create an instance of {@link MonPersonActivateResponse }
     */
    public MonPersonActivateResponse createMonPersonActivateResponse() {
        return new MonPersonActivateResponse();
    }

    /**
     * Create an instance of {@link MonPersonDisable }
     */
    public MonPersonDisable createMonPersonDisable() {
        return new MonPersonDisable();
    }

    /**
     * Create an instance of {@link MonPersonDisableResponse }
     */
    public MonPersonDisableResponse createMonPersonDisableResponse() {
        return new MonPersonDisableResponse();
    }

    /**
     * Create an instance of {@link MonPersonDisableList }
     */
    public MonPersonDisableList createMonPersonDisableList() {
        return new MonPersonDisableList();
    }

    /**
     * Create an instance of {@link MonPersonDisableListResponse }
     */
    public MonPersonDisableListResponse createMonPersonDisableListResponse() {
        return new MonPersonDisableListResponse();
    }

    /**
     * Create an instance of {@link MonPersonGetEventsList }
     */
    public MonPersonGetEventsList createMonPersonGetEventsList() {
        return new MonPersonGetEventsList();
    }

    /**
     * Create an instance of {@link MonPersonGetEventsListResponse }
     */
    public MonPersonGetEventsListResponse createMonPersonGetEventsListResponse() {
        return new MonPersonGetEventsListResponse();
    }

    /**
     * Create an instance of {@link GetPledgesByVIN }
     */
    public GetPledgesByVIN createGetPledgesByVIN() {
        return new GetPledgesByVIN();
    }

    /**
     * Create an instance of {@link GetPledgesByVINResponse }
     */
    public GetPledgesByVINResponse createGetPledgesByVINResponse() {
        return new GetPledgesByVINResponse();
    }

    /**
     * Create an instance of {@link GetPledgeReport }
     */
    public GetPledgeReport createGetPledgeReport() {
        return new GetPledgeReport();
    }

    /**
     * Create an instance of {@link GetPledgeReportResponse }
     */
    public GetPledgeReportResponse createGetPledgeReportResponse() {
        return new GetPledgeReportResponse();
    }

    /**
     * Create an instance of {@link GetLeasingReport }
     */
    public GetLeasingReport createGetLeasingReport() {
        return new GetLeasingReport();
    }

    /**
     * Create an instance of {@link GetLeasingReportResponse }
     */
    public GetLeasingReportResponse createGetLeasingReportResponse() {
        return new GetLeasingReportResponse();
    }

    /**
     * Create an instance of {@link GetStateContractReport }
     */
    public GetStateContractReport createGetStateContractReport() {
        return new GetStateContractReport();
    }

    /**
     * Create an instance of {@link GetStateContractReportResponse }
     */
    public GetStateContractReportResponse createGetStateContractReportResponse() {
        return new GetStateContractReportResponse();
    }

    /**
     * Create an instance of {@link Time }
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link TimeResponse }
     */
    public TimeResponse createTimeResponse() {
        return new TimeResponse();
    }

    /**
     * Create an instance of {@link GetForeignCompanyShortReport }
     */
    public GetForeignCompanyShortReport createGetForeignCompanyShortReport() {
        return new GetForeignCompanyShortReport();
    }

    /**
     * Create an instance of {@link GetForeignCompanyShortReportResponse }
     */
    public GetForeignCompanyShortReportResponse createGetForeignCompanyShortReportResponse() {
        return new GetForeignCompanyShortReportResponse();
    }

    /**
     * Create an instance of {@link GetForeignCompanyReport }
     */
    public GetForeignCompanyReport createGetForeignCompanyReport() {
        return new GetForeignCompanyReport();
    }

    /**
     * Create an instance of {@link GetForeignCompanyReportResponse }
     */
    public GetForeignCompanyReportResponse createGetForeignCompanyReportResponse() {
        return new GetForeignCompanyReportResponse();
    }

    /**
     * Create an instance of {@link GetForeignCompanyStructure }
     */
    public GetForeignCompanyStructure createGetForeignCompanyStructure() {
        return new GetForeignCompanyStructure();
    }

    /**
     * Create an instance of {@link GetForeignCompanyStructureResponse }
     */
    public GetForeignCompanyStructureResponse createGetForeignCompanyStructureResponse() {
        return new GetForeignCompanyStructureResponse();
    }

    /**
     * Create an instance of {@link GetForeignCompanyCoownersHistory }
     */
    public GetForeignCompanyCoownersHistory createGetForeignCompanyCoownersHistory() {
        return new GetForeignCompanyCoownersHistory();
    }

    /**
     * Create an instance of {@link GetForeignCompanyCoownersHistoryResponse }
     */
    public GetForeignCompanyCoownersHistoryResponse createGetForeignCompanyCoownersHistoryResponse() {
        return new GetForeignCompanyCoownersHistoryResponse();
    }

    /**
     * Create an instance of {@link GetCompanyShortReportUA }
     */
    public GetCompanyShortReportUA createGetCompanyShortReportUA() {
        return new GetCompanyShortReportUA();
    }

    /**
     * Create an instance of {@link GetCompanyShortReportUAResponse }
     */
    public GetCompanyShortReportUAResponse createGetCompanyShortReportUAResponse() {
        return new GetCompanyShortReportUAResponse();
    }

    /**
     * Create an instance of {@link GetCompanyExtendedReportUA }
     */
    public GetCompanyExtendedReportUA createGetCompanyExtendedReportUA() {
        return new GetCompanyExtendedReportUA();
    }

    /**
     * Create an instance of {@link GetCompanyExtendedReportUAResponse }
     */
    public GetCompanyExtendedReportUAResponse createGetCompanyExtendedReportUAResponse() {
        return new GetCompanyExtendedReportUAResponse();
    }

    /**
     * Create an instance of {@link GetCompanyStructureUA }
     */
    public GetCompanyStructureUA createGetCompanyStructureUA() {
        return new GetCompanyStructureUA();
    }

    /**
     * Create an instance of {@link GetCompanyStructureUAResponse }
     */
    public GetCompanyStructureUAResponse createGetCompanyStructureUAResponse() {
        return new GetCompanyStructureUAResponse();
    }

    /**
     * Create an instance of {@link GetCompanyCoownersHistoryUA }
     */
    public GetCompanyCoownersHistoryUA createGetCompanyCoownersHistoryUA() {
        return new GetCompanyCoownersHistoryUA();
    }

    /**
     * Create an instance of {@link GetCompanyCoownersHistoryUAResponse }
     */
    public GetCompanyCoownersHistoryUAResponse createGetCompanyCoownersHistoryUAResponse() {
        return new GetCompanyCoownersHistoryUAResponse();
    }

    /**
     * Create an instance of {@link GetCompanyShortReportKZ }
     */
    public GetCompanyShortReportKZ createGetCompanyShortReportKZ() {
        return new GetCompanyShortReportKZ();
    }

    /**
     * Create an instance of {@link GetCompanyShortReportKZResponse }
     */
    public GetCompanyShortReportKZResponse createGetCompanyShortReportKZResponse() {
        return new GetCompanyShortReportKZResponse();
    }

    /**
     * Create an instance of {@link GetCompanyStructureKZ }
     */
    public GetCompanyStructureKZ createGetCompanyStructureKZ() {
        return new GetCompanyStructureKZ();
    }

    /**
     * Create an instance of {@link GetCompanyStructureKZResponse }
     */
    public GetCompanyStructureKZResponse createGetCompanyStructureKZResponse() {
        return new GetCompanyStructureKZResponse();
    }

    /**
     * Create an instance of {@link GetCompanyCoownersHistoryKZ }
     */
    public GetCompanyCoownersHistoryKZ createGetCompanyCoownersHistoryKZ() {
        return new GetCompanyCoownersHistoryKZ();
    }

    /**
     * Create an instance of {@link GetCompanyCoownersHistoryKZResponse }
     */
    public GetCompanyCoownersHistoryKZResponse createGetCompanyCoownersHistoryKZResponse() {
        return new GetCompanyCoownersHistoryKZResponse();
    }

}
